#!/usr/bin/env python3
"""Emit bounded evidence for the audit of ab6f6c9..9b0d5a3. Never run Muse.

Usage from the repo root:
  python3 scripts/collect-commit-audit.py > evidence/17-commit-audit.txt
Requires the original local extraction directories; no network or account needed.
"""
import hashlib
from pathlib import Path
import plistlib
import re

ROOT = Path(__file__).resolve().parent.parent
JAVA = "extracted-apk/jadx/sources/"
APP = "com/facebook/aura/"


def excerpt(relative, ranges):
    path = ROOT / relative
    raw = path.read_bytes()
    lines = raw.decode().splitlines()
    print(f"\n## {relative}\nsha256: {hashlib.sha256(raw).hexdigest()}")
    for start, end in ranges:
        if not 1 <= start <= end <= len(lines):
            raise ValueError(f"Invalid range: {relative}:{start}-{end}")
        print(f"-- lines {start}-{end} --")
        for index in range(start - 1, end):
            print(f"{index + 1}: {lines[index]}".rstrip())


print("# Review of ab6f6c9, 36f0c2b, 9b0d5a3: primary static excerpts")
print("# Generated by scripts/collect-commit-audit.py; no app execution.")
print("# JADX is a reconstruction; coroutine control flow can be incorrect.")
print("# See COMMIT-AUDIT.md for interpretation and unresolved questions.")
for relative, ranges in [
    ("nodes/core/NodeHitlCatalog.java", [(25, 75), (258, 299)]),
    ("nodes/core/NodeCommandId.java", [(20, 35)]),
    ("commands/geofence/GeofenceSetHandler.java", [(96, 109)]),
    ("commands/network/NetworkStateHandlerKt.java", [(95, 112)]),
    ("permissions/defaults/PermissionDefaultMode.java", [(28, 43)]),
    ("permissions/defaults/PermissionSettingsRepository.java", [(307, 314)]),
    ("permissions/defaults/PermissionSettingsRepository$update$2.java", [(114, 132)]),
    ("gateway/HatchNodeHitlGate.java", [(476, 500)]),
    ("nodes/datasource/DataSourcePublishPipelineKt.java", [(6, 14)]),
    ("nodes/datasource/DataSourcePublishPipeline.java", [(80, 108), (160, 175), (532, 555)]),
]:
    excerpt(JAVA + APP + relative, ranges)
excerpt(JAVA + "X/C5xi.java", [(83, 86)])
excerpt("extracted/Muse.app/Contents/Resources/chrome/lib/connection.js",
        [(129, 151), (237, 265)])

app = ROOT / "extracted-ipa/Payload/HatchApp.app"
if not app.exists():
    apps = list((ROOT / "extracted-ipa/Payload").glob("*.app"))
    if len(apps) != 1:
        raise ValueError("Expected exactly one iOS app")
    app = apps[0]
info = plistlib.loads((app / "Info.plist").read_bytes())
binary = app / info["CFBundleExecutable"]
raw = binary.read_bytes()
print(f"\n## {binary.relative_to(ROOT)}\nsha256: {hashlib.sha256(raw).hexdigest()}")
print("# Literal byte matches only; no active trust root or network use established.")
for marker in [b"rekor.sigstage.dev", b"rekor.sigstore.dev",
               b"NoiseAlwaysAcceptAttestationVerifier", b"NoiseSevSnpAttestationVerifier",
               b"initWithSevSnpVerifierEnabled", b"Unallowed OHAI GraphQL query"]:
    offsets = [m.start() for m in re.finditer(re.escape(marker), raw)]
    print(f"{marker.decode()}: {len(offsets)} matches; first byte offsets {offsets[:5]}")
roots = plistlib.loads((app / "CACerts.plist").read_bytes())
print(f"CACerts.plist: {len(roots)} entries (presence does not establish selection)")
